import pandas as pd
from typing import Dict, Any

class InventorySimulator:
    """
    Applies the Baseline and Proposed Inventory Policies to the historical test set.
    """
    def __init__(self, config: Dict[str, Any]):
        self.config = config

    def apply_policies(self, df_dashboard: pd.DataFrame, df_features: pd.DataFrame) -> pd.DataFrame:
        """
        Merge features with dashboard predictions and compute physical order quantities.
        """
        df = df_dashboard.copy()
        
        # Bring in required features for cost and scenarios
        df["sell_price"] = df_features["sell_price"].values
        df["has_any_event"] = df_features["has_any_event"].values
        df["rolling_std_28"] = df_features["rolling_std_28"].values
        
        # Baseline Policy: Order exactly the point forecast
        df["Baseline_Order"] = df["point"].round().clip(lower=0)
        
        # Intelligent Policy: Order the Recommended_Stock_Level generated by the Decision Engine
        df["Proposed_Order"] = df["Recommended_Stock_Level"].round().clip(lower=0)
        
        return df
